### ISSUE TITLE
Add option for selecting execution engine

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-api#132]
Add a query parameter to when starting builds to select the execution engine. Such as:

```http
POST /api/project/{projectId}/build?engine=wharf-cmd
```

The value possible here should come from the configs. Such as:

```yaml
ci:
  defaultEngine: jenkins
  engines:
    jenkins:
      name: Jenkins
      triggerUrl: https://jenkins.local/whatever
      triggerToken: changeit
    wharf-cmd:
      name: wharf-cmd
      triggerUrl: http://wharf-cmd-provisioner
      triggerToken: changeit
```

Needs backwards compatbility, so if defining `ci.triggerUrl` and `ci.triggerToken` (the existing config fields) then that should be equivalent to:

```yaml
ci:
  # old fields:
  triggerUrl: https://jenkins.local/whatever
  triggerToken: changeit

  # are translated to the following:
  defaultEngine: unnamed
  engines:
    unnamed:
      name: Unnamed
      triggerUrl: https://jenkins.local/whatever
      triggerToken: changeit
```

There should also be new endpoints for accessing these endpoints, so the frontend can display a way to select between them:

```http
GET /api/engine
```

Response:

```json
{
  "default": "jenkins",
  "engines": {
    "jenkins": {
      "name": "Jenkins",
      "triggerUrl": "https://jenkins.local/whatever"
    },
    "wharf-cmd": {
      "name": "wharf-cmd",
      "triggerUrl": "http://wharf-cmd-provisioner"
    }
  }
}
```

The response cannot include the tokens. But the URLs are safe to share and can be used to give more context to the user.

**Comment by jilleJr** [comment]
Viper doesn't play well with environment variables of unknown keys, such as in maps or slices. Need to rethink this.

**Comment by Alexamakans** [comment]
👍🏻 

Suggest changing endpoint to `GET /api/engine` instead to match the "no plural endpoints" design that we have now.

**Comment by jilleJr** [comment]
New design:

```yaml
ci:
  engine:
    name: Jenkins # Defaults to "Primary"
    triggerUrl: https://jenkins.local/whatever
    triggerToken: changeit
  engine2:
    name: wharf-cmd # Defaults to "Secondary"
    triggerUrl: http://wharf-cmd-provisioner
    triggerToken: changeit
```

It's a little bit clunky, but it's what we can do with Viper's restrictions right now. I find it an OK workaround instead of trying to update wharf-core to use a different config provider and whatnot
